name 'wirbelsturm-common'
version '1.0.4'
source 'https://github.com/miguno/puppet-wirbelsturm_common.git'
author 'Michael G. Noll'
license 'Apache License, Version 2.0'
summary 'Module for managing and configuring common Wirbelsturm host settings'
description 'Module for managing and configuring common Wirbelsturm host settings'
project_page 'https://github.com/miguno/puppet-wirbelsturm_common'
#DISABLED SO WE DO NOT DEPEND ON PUPPETFORGE#dependency 'puppetlabs/ntp', '>= 3.0.3'
#DISABLED SO WE DO NOT DEPEND ON PUPPETFORGE#dependency 'puppetlabs/stdlib', '>= 4.1.0'
#DISABLED UNTIL PUBLISHED ON PUPPETFORGE#dependency 'miguno/puppet-sysctl'
